model SportsProjectFinalv1.0.mod;
data Distance.txt;
option solver gurobi;
solve;
display x;

set Teams := {'CAN', 'ICE', 'SWE', 'RUS', 'DEN', 'JAP', 'ANT', 'AUS', 'CHI', 'ARG', 'TAH', 'FIJ'} ordered;


# Generate output format

for {k in 1..K} {
    for {i in 1..I} {
        for {j in 1..J} {
            if (x[i,j,k] == 1) then
                printf "%s %s %d\n", member(j,Teams), member(i,Teams), k;
        }
    }
}

display x, y > OutputFile.csv;